# Application Parameters
spring.application.name=load_test_helper
server.port=8088
management.endpoints.web.exposure.include=*

# DB Connection Parameters
//spring.datasource.url=jdbc:h2:file:${user.dir}/db/${dbName}
spring.datasource.url=jdbc:postgresql://localhost:5432/${dbName}
spring.datasource.username=postgres
spring.datasource.password=password

# Database Parameters
spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialize=never
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

# Logging parameters
logging.level.root=INFO
logging.file.name=${user.dir}/logs/${spring.application.name}.log
logging.pattern.rolling-file-name=${user.dir}/logs/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
logging.file.max-size=10MB
logging.file.total-size-cap=100MB
logging.file.max-history=30

# Scheduler Parameters
spring.task.scheduling.pool.size=1

# Global constants
userDir=${user.dir}
serverListFile=serverList.dat
profileListFile=profileList.dat
dbName=load_test_helper
