spring.application.name=load_test_helper
server.port=8080
management.endpoints.web.exposure.include=*

//spring.datasource.url=jdbc:h2:file:${user.dir}/db/${dbName}
spring.datasource.url=jdbc:postgresql://localhost:5432/${dbName}
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.datasource.initialize=never

logging.level.root=INFO
logging.file.name=${user.dir}/logs/${spring.application.name}.log
logging.pattern.rolling-file-name=${user.dir}/logs/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
logging.file.max-size=10MB
logging.file.total-size-cap=100MB
logging.file.max-history=30

userDir=${user.dir}
serverListFile=serverList.dat
profileListFile=profileList.dat
dbName=load_test_helper
